name: Publish to GitHub Packages

env:
  PROJECT_PATH: 'MediatorCore/MediatorCore.csproj'
  NUGET_SOURCE: 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'
  
on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get Package Version
        id: package_version
        uses: battila7/get-version-action@v2

      - name: Set Package Version Env Variable
        run: echo "PACKAGE_VERSION=${{ steps.package_version.outputs.version-without-v }}" >> $GITHUB_ENV

      - name: Add GitHub NuGet Source
        run: |
          dotnet nuget add source ${{ env.NUGET_SOURCE }} \
            --username "${{ github.actor }}" \
            --password "${{ secrets.NUGET_PACKAGE_TOKEN }}" \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./nupkg
        
