name: Publish to GitHub Packages

env:
  PROJECT_PATH: 'MediatorCore/MediatorCore.csproj'
  NUGET_SOURCE: 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'
  
on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: User Info
        run: echo '${{ github.actor }} ${{ env.NUGET_SOURCE }}'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./nupkg

      - name: Add GitHub NuGet Source
        run: dotnet nuget add source \
             --name github ${{ env.NUGET_SOURCE }}\
             --username ${{ github.actor }} \
             --password ${{ secrets.GITHUB_TOKEN }} \
             --store-password-in-clear-text      
