name: Manually Publish to GitHub Packages

env:
  PROJECT_PATH: 'MediatorCore/MediatorCore.csproj'
  NUGET_SOURCE: 'https://nuget.pkg.github.com/heinwinnaing/index.json'

on:
  workflow_dispatch:
    inputs:
      release_version: 
        required: true
        description: 'Specific version to use for the package (e.g., 1.0.0, 1.0.0-preview, 1.0.0-preview.1)'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Show Inputs
        run: |
          echo "Version: ${{ github.event.inputs.release_version }}"

      - name: Validate Inputs
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-preview\.[0-9]+)?$ ]]; then
            echo "❌ Invalid version format. Use semver like 1.0.0 or 1.0.0-preview.1"
            exit 1
          fi
        
